# Site settings
title: Code Design Decode
header-img: img/home-bg.png
email: kevinromoser@gmail.com
copyright_name: kromoser
description: > # this means to ignore newlines until "baseurl:"
  Thoughts about programming, designing, and the nature of life.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kromoser
learn_profile: kromoser
email_username: kevinromoser@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
